spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskmanagement
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: my-secret-key
  expiration: 86400000  # 24 hours